"""second migration test

Revision ID: 06b4a36e5b96
Revises: 395306c76d19
Create Date: 2020-09-02 15:05:03.600705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b4a36e5b96'
down_revision = '395306c76d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('average_viewers', 'streamer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('average_viewers', sa.Column('streamer', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
