"""heroku migrate

Revision ID: 230644aee241
Revises: 627beac55c75
Create Date: 2020-09-11 15:20:27.426846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230644aee241'
down_revision = '627beac55c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('average_viewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('streamer', sa.String(length=25), nullable=False),
    sa.Column('viewers', sa.Integer(), nullable=False),
    sa.Column('date_snapped', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('average_viewers')
    # ### end Alembic commands ###
