"""initial migration

Revision ID: 395306c76d19
Revises: 
Create Date: 2020-09-02 11:48:08.565844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395306c76d19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('average_viewers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('streamer', sa.String(length=25), nullable=False),
                    sa.Column('viewers', sa.Integer(), nullable=False),
                    sa.Column('date_snapped', sa.DateTime(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('average_viewers')
    # ### end Alembic commands ###
